version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    image: chernyybo/foodgram_backend:latest
    restart: always
    volumes:
      - static_dir:/app/static/
      - media_dir:/app/media/
    env_file:
      - ../.env

  frontend:
    image: chernyybo/foodgram_frontend:latest
    build: ../frontend
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/var/www/foodgram/static/
      - media_dir:/var/www/foodgram/media/
    depends_on:
      - backend
      - frontend

volumes:
  static_dir:
  media_dir:
  postgres_data:
